// <auto-generated />
using DKTinChi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DKTinChi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DKTinChi.Models.modelDangKy", b =>
                {
                    b.Property<int>("IdDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDangKy"));

                    b.Property<string>("IdSinhVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdTinChi")
                        .HasColumnType("int");

                    b.Property<int>("SoTinDaDangKy")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdDangKy");

                    b.HasIndex("IdSinhVien");

                    b.HasIndex("IdTinChi");

                    b.ToTable("DangKys");
                });

            modelBuilder.Entity("DKTinChi.Models.modelSinhVien", b =>
                {
                    b.Property<string>("IdSinhVien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSinhVien");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("DKTinChi.Models.modelTinChi", b =>
                {
                    b.Property<int>("IdTinChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTinChi"));

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TenTinChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTinChi");

                    b.ToTable("TinChis");
                });

            modelBuilder.Entity("DKTinChi.Models.modelDangKy", b =>
                {
                    b.HasOne("DKTinChi.Models.modelSinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("IdSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DKTinChi.Models.modelTinChi", "TinChi")
                        .WithMany()
                        .HasForeignKey("IdTinChi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SinhVien");

                    b.Navigation("TinChi");
                });
#pragma warning restore 612, 618
        }
    }
}
